### ISSUE TITLE
[FEATURE] Searching Books 

### ISSUE THREAD

**Issue by rishabhrawat05** [ajaynegi45/LibraryMan-API#103]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Searching will help people to find books more easily and efficiently. So I want to add a function in book controller to search book by title,author or description. Please assign this issue to me 

### Feature Description

Searching will help people to find books more easily and efficiently. Please assign this issue to me 

### Would you like to work on this feature?

Yes

### Implementation Plan

So I want to add a function in book controller to search book by title,author or description

**Comment by Guhapriya01** [comment]
Hi @rishabhrawat05, thanks for the feature request! This sounds like a valuable feature. I'll go ahead and assign it to you. Let me know if you need any help on implementation.
