### ISSUE TITLE
[FEATURE] Send Reminder Notifications 2 Days Before Book Due Date

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/LibraryMan-API#25]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, the LibraryMan project does not have a feature that sends a reminder to members to return their borrowed books before the due date. This can lead to overdue books and inconvenience both members and the library staff. A reminder system would improve user experience and help ensure timely book returns.

### Feature Description

The proposed feature would send a notification to members 2 days before their book's due date, reminding them to return the book on time.

**Comment by JanelleW03** [comment]
is this still open? I would like to contribute

**Comment by ajaynegi45** [comment]
> is this still open? I would like to contribute

@JanelleW03 Yes, this issue is still open, and I'd love for you to contribute!. The labeled 'status: ready for dev', means you're welcome to ask for the issue to be assigned to you (if it hasn't been assigned already). Let me know if you're interested and we can discuss further!"

**Comment by Jenish-1235** [comment]
Hello there, I can work on this issue. I would love to contribute to this. Can we have further discussion?

**Comment by ajaynegi45** [comment]
> Hello there, I can work on this issue. I would love to contribute to this. Can we have further discussion?

Hello @Jenish-1235,

Yes, you can definitely start working on this issue. Before you proceed, could you please explain how you plan to implement the reminder feature? I'd like to understand your approach, how you'll handle the timing (sending reminders 2 days before the due date).

Looking forward to hearing your plan!

**Comment by TalupulaSahithi** [comment]
I want to work on this issue . Could you please assign me this .

**Comment by Shetu003** [comment]
Hello Sir, Could you please assign me this issue.

**Comment by ajaynegi45** [comment]
> Hello Sir, Could you please assign me this issue.

Hello @Shetu003,

Yes, I can definitely assign this issue to you. Before I assign this issue, could you please explain how you plan to implement the reminder feature? I'd like to understand your approach and how you'll handle the timing (sending reminders 2 days before the due date).

Looking forward to hearing your plan!

**Comment by Shetu003** [comment]
Sure Sir, To implement the Send Reminder Notifications 2 Days Before Book Due Date we can Set up a scheduler to run daily and Query borrowings due in 2 days without a sent reminder then we can use remaindernotification for this issue.

**Comment by Rohityadav9575** [comment]
hi sir could you assign this issue to me .My approach is =your project  have a column called dueDate in our borrowing table. This column keeps track of when each borrowed book is due to be returned.I set up a daily scheduler that runs automatically. This scheduler checks the borrowing table every day to see which books are due in 2 days.Once we find the books that are due soon, we send a notification to all the members who borrowed those books. This reminder helps them remember to return their books on time.

**Comment by ajaynegi45** [comment]
> hi sir could you assign this issue to me .My approach is =your project have a column called dueDate in our borrowing table. This column keeps track of when each borrowed book is due to be returned.I set up a daily scheduler that runs automatically. This scheduler checks the borrowing table every day to see which books are due in 2 days.Once we find the books that are due soon, we send a notification to all the members who borrowed those books. This reminder helps them remember to return their books on time.

Hi @Rohityadav9575,

Thank you for expressing your interest in working on the "`Send Reminder Notifications 2 Days Before Book Due Date`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.
