### ISSUE TITLE
[BUG] Missing Code_of_Conduct.md

### ISSUE THREAD

**Issue by shubhagarwal1** [ajaynegi45/LibraryMan-API#40]
### Bug Description

Missing Code_of_Conduct.md
please assign me this task @ajaynegi45 with label (gssoc-ext, level)

**Comment by ajaynegi45** [comment]
> ### Bug Description
> Missing Code_of_Conduct.md please assign me this task @ajaynegi45 with label (gssoc-ext, level)

Hi @shubhagarwal1,

Thank you for expressing your interest in working on the "`Missing Code_of_Conduct.md`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by shubhagarwal1** [comment]
> > ### Bug Description
> > Missing Code_of_Conduct.md please assign me this task @ajaynegi45 with label (gssoc-ext, level)
> 
> Hi @shubhagarwal1,
> 
> Thank you for expressing your interest in working on the "`Missing Code_of_Conduct.md`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.
> 
> Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

please add level tag also

**Comment by ajaynegi45** [comment]
> > > ### Bug Description
> > > Missing Code_of_Conduct.md please assign me this task @ajaynegi45 with label (gssoc-ext, level)
> > 
> > 
> > Hi @shubhagarwal1,
> > Thank you for expressing your interest in working on the "`Missing Code_of_Conduct.md`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.
> > Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.
> 
> please add level tag also @ajaynegi45

what is level tag?

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
