### ISSUE TITLE
Missing Contributing.md

### ISSUE THREAD

**Issue by samyak-aditya** [ajaynegi45/LibraryMan-API#41]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

Missing Contributing.md
please assign me this task @ajaynegi45 with label (gssoc-ext, level)

### Would you like to work on this issue?

Yes

**Comment by ajaynegi45** [comment]
> ### Is this a new issue?
> * [x]  I have searched "open" and "closed" issues, and this is not a duplicate.
> 
> ### Bug Description
> Missing Contributing.md please assign me this task @ajaynegi45 with label (gssoc-ext, level)
> 
> ### Would you like to work on this issue?
> Yes

Hi @samyak-aditya,

Thank you for expressing your interest in working on the "`Missing Contributing.md`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by ajaynegi45** [comment]
Hi @SaanyaGarg5,

Thank you for expressing your interest in working on the "Missing Contributing.md" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by samyak-aditya** [comment]
Hey @ajaynegi45 Kindly check the PR I have fixed the issue assigned to me
