### ISSUE TITLE
[FEATURE] Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [ajaynegi45/LibraryMan-API#49]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @ajaynegi45 please assign me this task

### Would you like to work on this feature?

Yes

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Feature Description
> I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
> 
> Hey @ajaynegi45 please assign me this task
> 
> ### Would you like to work on this feature?
> Yes

Hi @samyak-aditya,

Thank you for expressing your interest in working on the "`Automated Greeting Workflow`" issue. I'm delighted to inform you that I have assigned this issue to you. Your willingness to contribute to our project is much appreciated. 

If you have any other GitHub workflows that could help guide new contributors, or if you know of any bots that can assign tasks, edit labels, reply automatically, or perform similar tasks, feel free to share them with me. I'm open to starting work on it.

Feel free to start working, and if you have any questions or need assistance during the process, please don't hesitate to reach out.

**Comment by samyak-aditya** [comment]
Hey @ajaynegi45 I have raised the PR
Thanks
