### ISSUE TITLE
Enhancing readme

### ISSUE THREAD

**Issue by Aditijainnn** [ajaynegi45/LibraryMan-API#62]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

Enchance readme adding contributors profiles, dropdown features and go to top toggle
please assign this to me under gssoc ext and hacktoberfest

### Would you like to work on this feature?

Yes

**Comment by ajaynegi45** [comment]
https://github.com/ajaynegi45/LibraryMan-API/issues/28
