### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by shreya-paul-17** [ajaynegi45/LibraryMan-API#66]
### Is this a new issue?

- [X] I have searched "open" and "closed" issues, and this is not a duplicate.

### Bug Description

Dear Project Admin, 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

### Would you like to work on this issue?

Yes

**Comment by Devamani11D** [comment]
Hey @shreya-paul-17 ,
We will add the required labels to the project soon!! Thank you for bringing it to our notice.

**Comment by ajaynegi45** [comment]
> Hey @ajaynegi45 , I think i dont have access to add required topic names to the project! I have checked the labels and these two are missing -> hacktoberfest-accepted and gssoc-ext. And i think if our project is not in gssoc normal program, We can remove that gssoc label, It might cause confusion to contributors who wish to contribute in extended program.

We have all required labels
