### ISSUE TITLE
[FEATURE] Sidebar Navigation

### ISSUE THREAD

**Issue by archanasingh11** [ajaynegi45/LibraryMan-API#69]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Its a missing feature

### Feature Description

**Description:**

To enhance the user interface and improve navigation, I propose implementing a **collapsible sidebar menu** in the application. This feature will allow users to expand or collapse the sidebar for a more streamlined experience, especially on smaller screens or when a more focused view is required.

### Benefits:

- **Improved Usability:** Collapsible sidebars will provide users with the flexibility to hide the menu when it's not needed, freeing up more screen space for content. This will be particularly beneficial for users who prefer a minimalist interface.
- **Enhanced Responsiveness:** This feature will optimize the application for various screen sizes, especially for users on tablets or mobile devices, without compromising on functionality.
- **Modern Design:** The collapsible sidebar aligns with modern UI trends, offering an intuitive and user-friendly design that increases the overall appeal of the application.

### Proposed Features:

1. **Sidebar Toggle Button:**
   - Implement a toggle button that allows users to collapse or expand the sidebar menu.
   - Place the button strategically in the header or sidebar for easy access.

2. **Dynamic Sidebar Width:**
   - When collapsed, the sidebar will reduce to an icon-only view, preserving key navigation functions while saving space.
   - Upon expansion, the sidebar will display full menu labels alongside the icons.

3. **Smooth Animation:**
   - Add smooth transition effects for collapsing and expanding the sidebar to enhance the visual experience.
   
4. **Responsive Design:**
   - Ensure that the collapsible sidebar is responsive and works seamlessly across different devices and screen sizes.
   - Sidebar should default to collapsed on smaller screens to maximize space for content.

5. **State Persistence:**
   - Store the sidebar state (collapsed/expanded) in local storage so that the user’s preference persists across sessions.

6. **Accessibility:**
   - Ensure that the sidebar remains fully accessible, with proper focus states and keyboard navigation support when collapsed.

### Would you like to work on this feature?

Yes

### Task Breakdown:

- Design the sidebar to collapse and expand with a toggle button.
- Apply animations for smooth transitions.
- Make necessary changes to CSS/SCSS to accommodate both expanded and collapsed states.
- Implement responsive behavior for mobile and tablet views.
- Store the user's preference using local storage or cookies to persist the sidebar state across sessions.
- Test on multiple devices to ensure consistent behavior and experience.

Please @ajaynegi45 assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

**Comment by ajaynegi45** [comment]
> ### Is this feature already requested?
> * [x]  I have checked "open" and "closed" issues, and this is not a duplicate.
> 
> ### Problem or Missing Functionality
> Its a missing feature
> 
> ### Feature Description
> **Description:**
> 
> To enhance the user interface and improve navigation, I propose implementing a **collapsible sidebar menu** in the application. This feature will allow users to expand or collapse the sidebar for a more streamlined experience, especially on smaller screens or when a more focused view is required.
> 
> ### Benefits:
> * **Improved Usability:** Collapsible sidebars will provide users with the flexibility to hide the menu when it's not needed, freeing up more screen space for content. This will be particularly beneficial for users who prefer a minimalist interface.
> * **Enhanced Responsiveness:** This feature will optimize the application for various screen sizes, especially for users on tablets or mobile devices, without compromising on functionality.
> * **Modern Design:** The collapsible sidebar aligns with modern UI trends, offering an intuitive and user-friendly design that increases the overall appeal of the application.
> 
> ### Proposed Features:
> 1. **Sidebar Toggle Button:**
>    
>    * Implement a toggle button that allows users to collapse or expand the sidebar menu.
>    * Place the button strategically in the header or sidebar for easy access.
> 2. **Dynamic Sidebar Width:**
>    
>    * When collapsed, the sidebar will reduce to an icon-only view, preserving key navigation functions while saving space.
>    * Upon expansion, the sidebar will display full menu labels alongside the icons.
> 3. **Smooth Animation:**
>    
>    * Add smooth transition effects for collapsing and expanding the sidebar to enhance the visual experience.
> 4. **Responsive Design:**
>    
>    * Ensure that the collapsible sidebar is responsive and works seamlessly across different devices and screen sizes.
>    * Sidebar should default to collapsed on smaller screens to maximize space for content.
> 5. **State Persistence:**
>    
>    * Store the sidebar state (collapsed/expanded) in local storage so that the user’s preference persists across sessions.
> 6. **Accessibility:**
>    
>    * Ensure that the sidebar remains fully accessible, with proper focus states and keyboard navigation support when collapsed.
> 
> ### Screenshots
> _No response_
> 
> ### Would you like to work on this feature?
> Yes
> 
> ### Implementation Plan
> ### Task Breakdown:
> * Design the sidebar to collapse and expand with a toggle button.
> * Apply animations for smooth transitions.
> * Make necessary changes to CSS/SCSS to accommodate both expanded and collapsed states.
> * Implement responsive behavior for mobile and tablet views.
> * Store the user's preference using local storage or cookies to persist the sidebar state across sessions.
> * Test on multiple devices to ensure consistent behavior and experience.
> 
> Please @ajaynegi45 assign me this task with labels "GSSOC-Ext", "hacktoberfest-accepted" and "level2".

This is backend not frontend. Make this issue here https://github.com/ajaynegi45/LibraryMan
