### ISSUE TITLE
[FEATURE] Adding Backend Functionality for Newsletter Signup Form

### ISSUE THREAD

**Issue by shreya5653** [ajaynegi45/LibraryMan-API#73]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

The newsletter signup form currently lacks backend functionality, preventing users from receiving confirmation of their submissions and storing subscriber data. This can lead to confusion. By implementing this feature, we can enhance user experience with immediate feedback and ensure secure data storage. This will also help us manage our subscriber list effectively, eliminating duplicates and allowing for targeted communications in the future. Overall, these improvements will create a smoother and more engaging experience for users.

### Feature Description

The newsletter signup functionality allows users to easily subscribe via a simple form that captures their email for secure storage in our database. This feature enhances engagement by providing instant confirmation of their subscription, fostering a stronger connection with our organization. Users benefit from immediate acknowledgment of their subscription and personalized communication through relevant updates, ultimately enriching their experience and strengthening our communication strategy.

### Would you like to work on this feature?

Yes

### Implementation Plan

1. Create a 'NewsletterSubscriber' entity and database table for emails.  
2. Develop a service to validate and store email subscriptions.  
3. Update the controller to process submissions and send confirmation messages.

**Comment by shreya5653** [comment]
@ajaynegi45 I want to work on this issue please assign it to me and add labels.

**Comment by shreya5653** [comment]
@ajaynegi45 Can you please assign me this issue

**Comment by Guhapriya01** [comment]
@shreya5653, thank you for your detailed proposal! It's clear that adding backend functionality for the newsletter signup is important for enhancing user engagement.

I'll assign this issue to you so we can move forward with the implementation.

Do you have a plan for handling the actual sending of newsletters after implementing the backend?

**Comment by shreya5653** [comment]
@Guhapriya01, thank you for assigning me this task!   

I have a plan for adding the backend functionality. To handle the actual sending of emails there are a couple of approaches we can take: 

1.Using third-party email services like SendGrid, Mailchimp, or Postmark, which offer easy APIs and built-in tools for tracking and scalability.
2.Using an SMTP server (such as Gmail SMTP or AWS SES) to send emails directly from our backend.
However, I’m still exploring these options and not entirely sure which one would be the best fit for our use case. I’d appreciate your input or any suggestions on which approach might align better with the project’s goals.

Currently I am focused on making the backend functional for newsletter subscription.

**Comment by shreya5653** [comment]
@Guhapriya01, Thank you! I’ll start implementing the backend functionality for the newsletter signup. Once that’s done, we can discuss the email-sending methods. I’ll reach out if I need any help!

**Comment by shreya5653** [comment]
@Guhapriya01, I have a doubt. I added the code for the controller, but I’m not sure about the endpoints. Since the signup option is available on every page, I plan to display the confirmation message on the same page without any redirection.

Will this approach work for you? Also, do I need to integrate the frontend myself, or will someone else handle that if we add different controller endpoints?

**Comment by Guhapriya01** [comment]
@shreya5653, displaying the confirmation message on the same page sounds good, and we can go with that. Regarding the frontend, I’ll update you soon. In the meantime, you can start implementing the backend!

**Comment by shreya5653** [comment]
> @shreya5653, displaying the confirmation message on the same page sounds good, and we can go with that. However, I noticed that [Issue #90](https://github.com/ajaynegi45/LibraryMan/issues/90) related to the confirmation message in the frontend repo is already assigned to someone else. I’ll update you soon on how we can proceed. In the meantime, feel free to start implementing the backend!

@Guhapriya01, thank you for the update! I’ll proceed with implementing the backend as planned.

Please let me know if there are any changes. If there's any coordination needed to align the backend with the frontend work on Issue #90. I'd be happy to collaborate if required!

**Comment by shreya5653** [comment]
@Guhapriya01,

I’ve implemented the backend for the newsletter signup feature, including the entity, service, controller, and repository layers. I tested the endpoints via Postman, and everything is working fine with confirmation messages displaying correctly.

Kindly review the PR and assign it to me.

Thanks!
