### ISSUE TITLE
Validation of Api Values

### ISSUE THREAD

**Issue by anishmu20** [ajaynegi45/LibraryMan-API#81]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, the API does not validate user input properly. This means that when users or systems send requests, data is accepted without checks for correctness, format, or constraints. For instance, fields like email addresses, phone numbers, or dates can be incorrectly formatted, leading to inconsistent data being stored in the system.

### Feature Description

This feature adds input validation to the API to ensure that data received from client requests adheres to the defined constraints and business rules before processing. By validating inputs, the API can enforce data integrity, prevent invalid data from being persisted to the database, and improve security by mitigating the risk of malicious inputs.

### Would you like to work on this feature?

Yes

### Implementation Plan

To implement validation in Spring Boot, identify key fields in the DTO classes that require validation, such as required fields (e.g., name, email), formatted fields (e.g., email, phone), and fields with constraints (e.g., age, price, string length). Use standard validation annotations like @NotNull, @Size, @Email, and @Pattern to enforce these rules. Update the DTO classes with these annotations to ensure that all incoming data is validated before reaching the service layer. This helps maintain data integrity, improves user feedback, and prevents invalid data from being processed.

**Comment by Guhapriya01** [comment]
@anishmu20, thanks for the detailed implementation plan! Input validation is crucial for ensuring data integrity and security within the API, and I believe this enhancement could significantly improve our system.

I’d like to assign this request to you for implementation. If you need any assistance while working on this, feel free to reach out!

**Comment by Guhapriya01** [comment]
Hi @anishmu20! Just wanted to check in and see how the input validation work is going. Let me know if you need any help with the implementation!

**Comment by anishmu20** [comment]
hii sorry for delay i am working on it  will  be done in  next 2 to 3 days .

**Comment by Guhapriya01** [comment]
No problem, thanks for the update!
