### ISSUE TITLE
[FEATURE] Add Authentication and Authorization

### ISSUE THREAD

**Issue by Ishratnoori** [ajaynegi45/LibraryMan-API#93]
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Problem or Missing Functionality

Currently, there’s no authentication or authorization to control access based on user roles. Adding this will improve security and help manage actions specific to roles (e.g., admin, librarian, and member).

### Feature Description

I suggest implementing authentication with role-based access control. This feature will restrict certain actions based on user roles, ensuring that only authorized users can perform specific tasks. Using Spring Security, we can set up roles and permissions to add a layer of security and enhance user management.

### Would you like to work on this feature?

Yes

### Implementation Plan

I plan to use Spring Security to implement login, registration, and role-based access control. I'll define roles (e.g., admin, librarian, member) and set permissions accordingly to secure relevant endpoints.

**Comment by Guhapriya01** [comment]
Thank you @Ishratnoori for your feature request! 

The functionality you've suggested is already implemented in our current configuration. We’ve used Spring Security to secure endpoints and manage actions based on user roles (e.g., admin, librarian, member). Our `WebConfiguration` class includes all the necessary settings for secure access control, login, and session management.

Therefore, I’ll proceed to close this issue. If you have specific requirements or additional role configurations in mind, please let us know. Thanks for your interest in improving the project!
